apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: diary-app
spec:
  selector:
    app: diary-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
